#!/bin/bash

set -eu -o pipefail

# Allow removal of running kernel
sudo rm -f /usr/bin/lunx-check-removal
sudo ln -s /usr/bin/true /usr/bin/lunx-check-removal

# Remove kernel packages
sudo apt -y --purge remove linux-image-generic-hwe-20.04 "^linux-.*5\..*"

# Absolutely remove all kernels
sudo rm -f /boot/*5*

# Add base kernel after removing HWE kernel
sudo apt -y install linux-generic

# Build a slim initramfs
sudo sed -i 's/^MODULES=most/MODULES=dep/' /etc/initramfs-tools/initramfs.conf
sudo mkinitramfs -c xz -o /boot/initrd.img-*

# Remove kernel name map
sudo rm -f /boot/System.map*

# Remove old boot images
sudo rm -f /boot/*.old

# Remove extra kernel modules
sudo rm -rf /lib/modules/*/build
sudo rm -rf /lib/modules/*/kernel/sound
sudo rm -rf /lib/modules/*/kernel/zfs
sudo rm -rf /lib/modules/*/kernel/wireguard
sudo rm -rf /lib/modules/*/kernel/net/wireless
sudo rm -rf /lib/modules/*/kernel/net/bluetooth
sudo rm -rf /lib/modules/*/kernel/fs/ocfs2
sudo rm -rf /lib/modules/*/kernel/fs/btrfs
sudo rm -rf /lib/modules/*/kernel/fs/xfs
sudo rm -rf /lib/modules/*/kernel/fs/nfs
sudo rm -rf /lib/modules/*/kernel/fs/nls
sudo rm -rf /lib/modules/*/kernel/drivers/wireless
sudo rm -rf /lib/modules/*/kernel/drivers/bluetooth
sudo rm -rf /lib/modules/*/kernel/drivers/hwmon
sudo rm -rf /lib/modules/*/kernel/drivers/staging
sudo rm -rf /lib/modules/*/kernel/drivers/infiniband
sudo rm -rf /lib/modules/*/kernel/drivers/media
sudo rm -rf /lib/modules/*/kernel/drivers/scsi
sudo rm -rf /lib/modules/*/kernel/drivers/iio
sudo rm -rf /lib/modules/*/kernel/drivers/net/wireless
sudo rm -rf /lib/modules/*/kernel/drivers/net/usb
sudo rm -rf /lib/modules/*/kernel/drivers/net/can
sudo rm -rf /lib/modules/*/kernel/drivers/usb/misc
sudo rm -rf /lib/modules/*/kernel/drivers/usb/serial
sudo rm -rf /lib/modules/*/kernel/drivers/usb/gadget
sudo find /lib/modules/*/kernel/drivers/net/ethernet/ -mindepth 1 -maxdepth 1 -not -name intel -not -name amd -not -name realtek -exec rm -rf {} \;
sudo find /lib/modules/*/kernel/drivers/gpu/drm/ -mindepth 1 -maxdepth 1  -type d -not -name virtio -not -name vboxvideo -not -name cirrus -not -name vmwgfx -not -name qxl -not -name ttm -exec rm -rf {} \;

# Remove graphics drivers
# (Intel, Radeon, Nouveau)
sudo rm -f /usr/lib/x86_64-linux-gnu/dri/i* 
sudo rm -f /usr/lib/x86_64-linux-gnu/dri/r* 
sudo rm -f /usr/lib/x86_64-linux-gnu/dri/n*
sudo rm -f /usr/lib/x86_64-linux-gnu/dri/zlink_dri.so

# Remove firmware files unused by VM
sudo rm -rf /usr/lib/firmware

