#!/bin/bash

set -eu -o pipefail
shopt -s extglob

# Remove dependencies
sudo apt -y --purge autoremove

# Remove swapfile
sudo swapoff -a
sudo rm -f /swapfile
sudo sed -i 's/^\/swapfile/\#\/swapfile/' /etc/fstab

# Remove temp files
sudo apt clean
rm -rf /home/user/{.[!.],}*
sudo rm -rf /root/{.[!.],}*
sudo rm -rf /tmp/{.[!.],}*
sudo rm -rf /var/log/*
sudo rm -rf /var/backups/*
sudo rm -rf /var/cache/*
sudo rm -rf /var/lib/apt/lists
sudo rm -rf /var/lib/dpkg/*-old

# Remove backgrounds
sudo rm -rf /usr/share/backgrounds/*

# Remove locales
sudo rm -rf /usr/share/locale/!(en)

# Adjust Gnome settings
# Disable screen blanking
gsettings set org.gnome.desktop.session idle-delay 0
# Disable screen locking after suspend
gsettings set org.gnome.desktop.lockdown disable-lock-screen true
# Disable screen locking from screensaver
gsettings set org.gnome.desktop.screensaver lock-enabled false
# Use gradient background color
gsettings set org.gnome.desktop.background primary-color '#992233'
gsettings set org.gnome.desktop.background secondary-color '#550055'
gsettings set org.gnome.desktop.background color-shading-type vertical
gsettings set org.gnome.desktop.background picture-options 'none'
gsettings set org.gnome.desktop.background picture-uri ''
# Disable animations
gsettings set org.gnome.desktop.interface enable-animations false

# Add terminal to favorites
dconf write /org/gnome/shell/favorite-apps "['firefox.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop']"

# Recreate important paths that may have been deleted
mkdir /home/user/Desktop

# Set default editor
echo export EDITOR=micro > /home/user/.bashrc

# Add gnome extension
mkdir -p /home/user/.local/share/gnome-shell/extensions/vm-tweaks
cd /home/user/.local/share/gnome-shell/extensions/vm-tweaks && git clone https://github.com/jncraton/gnome-vm-tweaks && mv gnome-vm-tweaks/extension.js . && mv gnome-vm-tweaks/metadata.json . && rm -rf gnome-vm-tweaks

# Add `user` to vboxsf group to allow writing to virtualbox shared folders
sudo adduser user vboxsf

echo Restart gnome-shell session...
kill -3 $(pidof gnome-shell)
sleep 5
gnome-extensions enable vm-tweaks

sudo sync -f
sudo fstrim -A

echo Waiting 15 seconds before scrubbing free space...
sleep 15

# Zero free space
echo Scrubbing free space...
sudo dd bs=4M if=/dev/zero of=/var/tmp/empty || sudo rm -f /var/tmp/empty
sudo sync -f

echo "Powering off in 15 seconds..."
sleep 15

# Shut down
sudo shutdown now
